### ISSUE TITLE
It dosent work

### ISSUE THREAD

**Issue by jbdhibd** [JarLowrey/GodotWeapons#1]
Am i dumb because this literraly does not work.  Its a godot project, not a plugin.......
(I need this desperately)

**Comment by JarLowrey** [comment]
Ok post your project, code, or some sort of info and I'll help you troubleshoot. Did you see the gif/video in the readme?

**Comment by jbdhibd** [comment]
wow, sorry for the late reply here, i got by by not using this, i wrote this when i was a complte beginner at godot, thx for your help tho.
